runtime: php7.3
env: flex

runtime_config:
  document_root: public

skip_files:
  .env

env_variables:
  APP_NAME: Laravel
  APP_ENV: local
  APP_KEY: base64:h/mbh3MzdaCkH5BesFQIH5/C389AwM4qqMGjSgxgYgw=
  APP_DEBUG: true
  APP_URL: http://localhost

  LOG_CHANNEL: stack
  LOG_LEVEL: debug

  DB_CONNECTION: mysql
  DB_HOST: 34.126.96.73
  DB_PORT: 3306
  DB_DATABASE: star_office
  DB_USERNAME: root
  DB_PASSWORD: Bjsindonesia567*
