runtime: php74

handlers:
- url: /(.*\.(gif|png|jpg|css|js))$
  static_files: public/\1
  upload: public/.*\.(gif|png|jpg|css|js)$


env_variables:
  APP_NAME: Laravel
  APP_ENV: production
  APP_KEY: base64:M6Z34x0cz9hIuh1wZoByk2amjUlE6QL/BFMG90bscGo=
  APP_DEBUG: true
  APP_URL: https://bjs-staroffice.com/
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  LOG_LEVEL: debug
  LOG_CHANNEL: stderr 
  CACHE_DRIVER: database
  SESSION_DRIVER: cookie
  DB_DATABASE: star_office
  DB_USERNAME: root
  DB_PASSWORD: Bjsindonesia567*
  DB_SOCKET: "/cloudsql/jovial-sight-321203:asia-southeast1:bjs"
